import type { Drive, Application } from '@/types'

const companies = {
  genpact:   { id: 'c1',  name: 'Genpact',                    logo_url: 'https://logo.clearbit.com/genpact.com',       verified: true, industry: 'BPM' },
  capgemini: { id: 'c2',  name: 'Capgemini',                  logo_url: 'https://logo.clearbit.com/capgemini.com',     verified: true, industry: 'IT' },
  hdfc:      { id: 'c3',  name: 'HDFC Life',                  logo_url: 'https://logo.clearbit.com/hdfclife.com',      verified: true, industry: 'BFSI' },
  hpe:       { id: 'c4',  name: 'Hewlett Packard Enterprise',  logo_url: 'https://logo.clearbit.com/hpe.com',           verified: true, industry: 'IT' },
  kotak:     { id: 'c5',  name: 'Kotak Mahindra Bank',         logo_url: 'https://logo.clearbit.com/kotak.com',         verified: true, industry: 'BFSI' },
  tcs:       { id: 'c6',  name: 'TCS',                        logo_url: 'https://logo.clearbit.com/tcs.com',           verified: true, industry: 'IT' },
  wipro:     { id: 'c7',  name: 'Wipro',                      logo_url: 'https://logo.clearbit.com/wipro.com',         verified: true, industry: 'IT' },
  infosys:   { id: 'c8',  name: 'Infosys BPM',                logo_url: 'https://logo.clearbit.com/infosys.com',       verified: true, industry: 'BPM' },
  ltim:      { id: 'c9',  name: 'LTIMindtree',                logo_url: 'https://logo.clearbit.com/ltimindtree.com',   verified: true, industry: 'IT' },
  techm:     { id: 'c10', name: 'Tech Mahindra',              logo_url: 'https://logo.clearbit.com/techmahindra.com',  verified: true, industry: 'IT' },
  icici:     { id: 'c11', name: 'ICICI Bank',                 logo_url: 'https://logo.clearbit.com/icicibank.com',     verified: true, industry: 'BFSI' },
  sopra:     { id: 'c12', name: 'Sopra Steria',               logo_url: 'https://logo.clearbit.com/soprasteria.com',   verified: true, industry: 'IT' },
}

export const mockDrives: Drive[] = [
  {
    id: '1', company: companies.genpact, role: 'Customer Support Associate',
    location: 'Hyderabad, Telangana', city: 'Hyderabad', experience: '0-1 years',
    eligibility: 'Any Graduate', salary: '₹2.5 - 4 LPA', mode: 'Onsite',
    drive_date: '2026-05-14', drive_time: '10:00 AM – 4:00 PM',
    is_priority: true, is_active: true, created_at: '2026-05-11T06:00:00Z',
    posted_days_ago: 1,
    description: 'Genpact is hiring Customer Support Associates for their Hyderabad centre. Candidates will handle inbound queries, provide resolutions and maintain customer satisfaction scores.',
    skills: ['Communication', 'MS Office', 'Customer Service'],
    openings: 45,
  },
  {
    id: '2', company: companies.capgemini, role: 'Java Full Stack Developer',
    location: 'Bengaluru, Karnataka', city: 'Bengaluru', experience: '3-5 years',
    eligibility: 'B.E / B.Tech / MCA', salary: '₹8 - 14 LPA', mode: 'Hybrid',
    drive_date: '2026-05-15', drive_time: '10:00 AM – 2:00 PM',
    is_priority: true, is_active: true, created_at: '2026-05-10T08:00:00Z',
    posted_days_ago: 2,
    description: 'Capgemini is conducting a walk-in drive for experienced Java Full Stack Developers. You will work on enterprise-grade React + Spring Boot applications for global clients.',
    skills: ['Java', 'Spring Boot', 'React', 'SQL', 'REST APIs'],
    openings: 20,
  },
  {
    id: '3', company: companies.hdfc, role: 'Sales Development Manager',
    location: 'Mumbai, Maharashtra', city: 'Mumbai', experience: '1-3 years',
    eligibility: 'Any Graduate', salary: '₹4 - 7 LPA', mode: 'Onsite',
    drive_date: '2026-05-15', drive_time: '9:30 AM – 3:00 PM',
    is_priority: true, is_active: true, created_at: '2026-05-10T09:00:00Z',
    posted_days_ago: 2,
    description: 'HDFC Life is looking for dynamic Sales Development Managers who will manage insurance sales, onboard advisors and meet revenue targets in their territory.',
    skills: ['Sales', 'Communication', 'Insurance Knowledge'],
    openings: 30,
  },
  {
    id: '4', company: companies.hpe, role: 'Server Support Engineer',
    location: 'Bengaluru, Karnataka', city: 'Bengaluru', experience: '3-5 years',
    eligibility: 'B.E / B.Tech (CS / IT / ECE)', salary: '₹7 - 12 LPA', mode: 'Hybrid',
    drive_date: '2026-05-16', drive_time: '9:30 AM – 1:30 PM',
    is_priority: true, is_active: true, created_at: '2026-05-09T10:00:00Z',
    posted_days_ago: 3,
    description: 'HPE is hiring Server Support Engineers to provide L2/L3 support for ProLiant and Synergy server lines. Strong Linux and hardware troubleshooting skills required.',
    skills: ['Linux', 'Server Hardware', 'Networking', 'ITIL'],
    openings: 15,
  },
  {
    id: '5', company: companies.kotak, role: 'Acquisition Manager – CASA',
    location: 'Pune, Maharashtra', city: 'Pune', experience: '0-1 years',
    eligibility: 'Any Graduate', salary: '₹3 - 5 LPA', mode: 'Onsite',
    drive_date: '2026-05-16', drive_time: '10:00 AM – 3:00 PM',
    is_priority: true, is_active: true, created_at: '2026-05-09T11:00:00Z',
    posted_days_ago: 3,
    description: 'Kotak Mahindra Bank is hiring freshers for CASA acquisition roles. You will acquire new savings/current account customers, build relationships and cross-sell banking products.',
    skills: ['Sales', 'Communication', 'Banking Basics'],
    openings: 25,
  },
  {
    id: '6', company: companies.infosys, role: 'Process Associate – Finance & Accounting',
    location: 'Hyderabad, Telangana', city: 'Hyderabad', experience: '0-1 years',
    eligibility: 'B.Com / M.Com / MBA Finance', salary: '₹2.8 - 4.5 LPA', mode: 'Hybrid',
    drive_date: '2026-05-17', drive_time: '9:00 AM – 12:30 PM',
    is_priority: false, is_active: true, created_at: '2026-05-09T12:00:00Z',
    posted_days_ago: 3,
    description: 'Infosys BPM is looking for Finance Process Associates for their F&A division. You will handle AP/AR processing, reconciliations and month-end close activities.',
    skills: ['Accounting', 'Tally', 'MS Excel', 'Finance'],
    openings: 60,
  },
  {
    id: '7', company: companies.ltim, role: 'Senior Software Engineer – Full Stack',
    location: 'Bengaluru, Karnataka', city: 'Bengaluru', experience: '5-8 years',
    eligibility: 'B.E / B.Tech / MCA', salary: '₹15 - 22 LPA', mode: 'Hybrid',
    drive_date: '2026-05-17', drive_time: '9:30 AM – 1:00 PM',
    is_priority: true, is_active: true, created_at: '2026-05-08T08:00:00Z',
    posted_days_ago: 4,
    description: 'LTIMindtree is conducting a senior-level walk-in for Full Stack engineers proficient in React + Node.js. You will architect and deliver features for Fortune 500 clients.',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'Microservices'],
    openings: 10,
  },
  {
    id: '8', company: companies.techm, role: 'Network Engineer',
    location: 'Hyderabad, Telangana', city: 'Hyderabad', experience: '1-3 years',
    eligibility: 'B.E / B.Tech with CCNA', salary: '₹4 - 7 LPA', mode: 'Onsite',
    drive_date: '2026-05-18', drive_time: '9:00 AM – 1:00 PM',
    is_priority: false, is_active: true, created_at: '2026-05-08T09:00:00Z',
    posted_days_ago: 4,
    description: 'Tech Mahindra is hiring Network Engineers for their Hyderabad NOC. You will monitor, configure and troubleshoot enterprise network infrastructure for global clients.',
    skills: ['CCNA', 'Cisco', 'Routing & Switching', 'Networking'],
    openings: 18,
  },
  {
    id: '9', company: companies.icici, role: 'Relationship Manager – Retail Banking',
    location: 'Chennai, Tamil Nadu', city: 'Chennai', experience: '1-3 years',
    eligibility: 'Any Graduate / MBA', salary: '₹5 - 8 LPA', mode: 'Onsite',
    drive_date: '2026-05-18', drive_time: '9:30 AM – 2:00 PM',
    is_priority: false, is_active: true, created_at: '2026-05-07T10:00:00Z',
    posted_days_ago: 5,
    description: 'ICICI Bank is hiring Relationship Managers for retail banking. You will manage an HNI portfolio, offer financial planning advice and drive cross-sell revenue.',
    skills: ['Relationship Management', 'Banking', 'Sales', 'Communication'],
    openings: 22,
  },
  {
    id: '10', company: companies.sopra, role: 'SAP Consultant (MM/SD)',
    location: 'Noida, Uttar Pradesh', city: 'Delhi NCR',experience: '3-5 years',
    eligibility: 'Any Graduate with SAP Certification', salary: '₹10 - 18 LPA', mode: 'Hybrid',
    drive_date: '2026-05-19', drive_time: '9:30 AM – 1:30 PM',
    is_priority: true, is_active: true, created_at: '2026-05-07T11:00:00Z',
    posted_days_ago: 5,
    description: 'Sopra Steria is looking for experienced SAP MM/SD consultants for their digital transformation engagements. Minimum 2 full lifecycle implementations required.',
    skills: ['SAP MM', 'SAP SD', 'ABAP Basics', 'S/4HANA'],
    openings: 8,
  },
  {
    id: '11', company: companies.tcs, role: 'Software Engineer – .NET',
    location: 'Pune, Maharashtra', city: 'Pune', experience: '1-3 years',
    eligibility: 'B.E / B.Tech / MCA', salary: '₹5 - 9 LPA', mode: 'Hybrid',
    drive_date: '2026-05-20', drive_time: '10:00 AM – 3:00 PM',
    is_priority: false, is_active: true, created_at: '2026-05-06T08:00:00Z',
    posted_days_ago: 6,
    description: 'TCS is hiring .NET developers for their BFSI vertical. You will work on C# / ASP.NET Core applications and participate in the full SDLC.',
    skills: ['C#', 'ASP.NET Core', 'SQL Server', 'Azure', 'REST APIs'],
    openings: 35,
  },
  {
    id: '12', company: companies.wipro, role: 'Data Engineer',
    location: 'Bengaluru, Karnataka', city: 'Bengaluru', experience: '3-5 years',
    eligibility: 'B.E / B.Tech / M.Tech', salary: '₹10 - 16 LPA', mode: 'Hybrid',
    drive_date: '2026-05-20', drive_time: '9:00 AM – 1:00 PM',
    is_priority: false, is_active: true, created_at: '2026-05-06T09:00:00Z',
    posted_days_ago: 6,
    description: 'Wipro is conducting a walk-in drive for Data Engineers with hands-on experience on cloud data platforms. You will design and maintain ETL pipelines for analytics workloads.',
    skills: ['Python', 'Spark', 'AWS Glue', 'Redshift', 'SQL', 'Airflow'],
    openings: 12,
  },
]

export const mockApplications: Application[] = [
  { id: 'a1', drive: mockDrives[0], user_id: 'u1', status: 'shortlisted', applied_at: '2026-05-10T10:00:00Z' },
  { id: 'a2', drive: mockDrives[1], user_id: 'u1', status: 'applied',      applied_at: '2026-05-09T11:00:00Z' },
  { id: 'a3', drive: mockDrives[3], user_id: 'u1', status: 'applied',      applied_at: '2026-05-08T09:00:00Z' },
  { id: 'a4', drive: mockDrives[6], user_id: 'u1', status: 'selected',     applied_at: '2026-05-07T14:00:00Z' },
]

export const CITIES = ['Bengaluru', 'Hyderabad', 'Pune', 'Mumbai', 'Chennai', 'Delhi NCR', 'Noida', 'Kolkata']
export const EXPERIENCES = ['0-1 years', '1-3 years', '3-5 years', '5-8 years', '8-12 years', '12+ years']
export const MODES = ['Onsite', 'Hybrid', 'Remote']
